import { useState, useEffect } from 'react'
import { X, Search, Check, Copy, AlertTriangle, Droplet } from 'lucide-react'
import axios from 'axios'

// Register a new MUSE fragrance: pick one Library oil, confirm what will be
// created, done. The store codes are generated by the platform — see
// server/sm/routes/muse-fragrance.js for why that direction matters.
//
// The screen deliberately shows the codes BEFORE writing anything. Four
// products launched under the wrong code in August because nobody could see
// what was about to be created until after it existed.
//
// Publishing to Shopify is not wired yet (owner: platform first). So the last
// step hands over the three codes to copy, which is what unblocks the person
// creating the product on the store today.
function api() { return { headers: { Authorization: `Bearer ${localStorage.getItem('platform_token')}` } } }

const ROW = {
  display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px',
  background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 7,
}
const LABEL = {
  fontSize: 11, fontWeight: 700, color: 'var(--text-muted)',
  textTransform: 'uppercase', letterSpacing: 0.4,
}

export default function NewMuseFragranceModal({ onClose, onCreated, addToast }) {
  const [oils, setOils] = useState([])
  const [search, setSearch] = useState('')
  const [oil, setOil] = useState(null)
  const [preview, setPreview] = useState(null)
  const [loading, setLoading] = useState(false)
  const [title, setTitle] = useState('')
  const [skip, setSkip] = useState([])          // masters the user unticked
  // Which collection the fragrance is being registered into. Defaults to
  // Library because that is what every one of the 454 existing MUSE products
  // is; the ten Archive fragrances register in September and must be switched.
  // It is stored as business_unit, which decides reporting — segment keeps
  // deciding oil and production (owner decision, 2026-08-14).
  const [unit, setUnit] = useState('library')
  const [saving, setSaving] = useState(false)
  const [done, setDone] = useState(null)

  useEffect(() => {
    axios.get('/api/fragrance-library', { ...api(), params: { segment: 'MUSE' } })
      .then(r => setOils(r.data || []))
      .catch(() => addToast('Could not load the Fragrance Library', 'error'))
  }, [])

  async function pick(o) {
    setOil(o); setPreview(null); setLoading(true); setSkip([])
    try {
      const r = await axios.get('/api/muse-fragrance/preview', { ...api(), params: { oil_id: o.id } })
      setPreview(r.data)
      setTitle(r.data.title)
    } catch (e) {
      addToast(e.response?.data?.error || 'Could not read this oil', 'error')
      setOil(null)
    } finally { setLoading(false) }
  }

  async function register() {
    const formats = (preview.lines || []).map(l => l.master).filter(m => !skip.includes(m))
    if (!formats.length) return addToast('Choose at least one format', 'error')
    setSaving(true)
    try {
      const r = await axios.post('/api/muse-fragrance',
        { oil_id: oil.id, title: title.trim(), formats, business_unit: unit }, api())
      setDone(r.data)
      onCreated?.()
    } catch (e) {
      addToast(e.response?.data?.error || 'Could not register', 'error')
    } finally { setSaving(false) }
  }

  async function retryPublish() {
    setSaving(true)
    try {
      const r = await axios.post(`/api/muse-fragrance/${done.number}/publish`, {}, api())
      setDone({ ...done, store: { ok: true, product: r.data.product } })
      addToast('Created on Shopify as a draft')
    } catch (e) {
      addToast(e.response?.data?.error || 'Shopify still refused', 'error')
    } finally { setSaving(false) }
  }

  const shown = oils.filter(o =>
    !search || `${o.name} ${o.code}`.toLowerCase().includes(search.toLowerCase()))
  const lines = (preview?.lines || []).filter(l => !skip.includes(l.master))

  const copyAll = () => {
    navigator.clipboard.writeText((done.created || []).map(c => `${c.format}\t${c.sku}\t${c.price ?? ''}`).join('\n'))
    addToast('Codes copied')
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ maxWidth: 620 }} onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <div>
            <h2 style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Droplet size={16} color="var(--accent-text)" /> New MUSE Fragrance
            </h2>
            <p>{done ? 'Created — copy the codes into Shopify' : 'One oil in, three sellable formats out'}</p>
          </div>
          <button className="modal-close" onClick={onClose} aria-label="Close"><X size={14} /></button>
        </div>

        <div className="modal-body">
          {/* ── Done: hand over the codes ─────────────────────────────────── */}
          {done ? (
            <>
              {done.store?.ok ? (
                <div style={{ ...ROW, background: 'rgba(74,222,128,0.08)', borderColor: 'rgba(74,222,128,0.25)', marginBottom: 14 }}>
                  <Check size={16} color="#4ade80" style={{ flexShrink: 0 }} />
                  <div style={{ fontSize: 12, color: '#4ade80', lineHeight: 1.5 }}>
                    <strong>{done.title}</strong> registered as number {done.number} and created on Shopify as a
                    <strong> draft</strong>. Marketing finishes the images, description and metafields, then activates it.
                  </div>
                </div>
              ) : (
                // The platform record stands either way — that is the point of
                // publishing after the commit. Say what to do next, plainly.
                <div style={{ ...ROW, alignItems: 'flex-start', background: 'rgba(251,191,36,0.07)', borderColor: 'rgba(251,191,36,0.2)', marginBottom: 14 }}>
                  <AlertTriangle size={16} color="#fbbf24" style={{ flexShrink: 0, marginTop: 1 }} />
                  <div style={{ fontSize: 12, color: '#fbbf24', lineHeight: 1.5 }}>
                    <strong>{done.title}</strong> is registered here as number {done.number}, but the Shopify product
                    was <strong>not</strong> created: {done.store?.error || 'publishing is switched off'}.
                    <br />Nothing is lost — retry below, or create it on the store with the codes shown.
                  </div>
                </div>
              )}
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {(done.created || []).map(c => (
                  <div key={c.sku} style={ROW}>
                    <span style={{ ...LABEL, width: 110 }}>{c.format}</span>
                    <span style={{ fontFamily: 'monospace', fontSize: 13, fontWeight: 700, color: 'var(--text-primary)', flex: 1 }}>{c.sku}</span>
                    <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
                      {c.price != null ? `$${Number(c.price).toFixed(2)}` : '—'}
                    </span>
                  </div>
                ))}
              </div>
            </>
          ) : !oil ? (
            /* ── Step 1: pick the oil ──────────────────────────────────────── */
            <>
              <div style={{ position: 'relative', marginBottom: 12 }}>
                <Search size={14} style={{ position: 'absolute', left: 11, top: 11, color: 'var(--text-muted)' }} />
                <input
                  autoFocus value={search} onChange={e => setSearch(e.target.value)}
                  placeholder="Search the Fragrance Library…"
                  style={{ width: '100%', padding: '9px 12px 9px 32px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 7, color: 'var(--text-primary)', fontSize: 13 }}
                />
              </div>
              <div style={{ maxHeight: 340, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 6 }}>
                {shown.length === 0 && (
                  <div style={{ padding: 20, textAlign: 'center', fontSize: 12, color: 'var(--text-muted)' }}>
                    {oils.length ? 'No oil matches that search.' : 'Loading the Fragrance Library…'}
                  </div>
                )}
                {shown.slice(0, 80).map(o => (
                  <button key={o.id} onClick={() => pick(o)} style={{ ...ROW, cursor: 'pointer', textAlign: 'left', width: '100%' }}>
                    <span style={{ fontFamily: 'monospace', fontSize: 11, color: 'var(--text-muted)', width: 84 }}>{o.code}</span>
                    <span style={{ fontSize: 13, color: 'var(--text-primary)', flex: 1 }}>{o.name}</span>
                    <span style={{ fontSize: 11, color: Number(o.current_stock) > 0 ? 'var(--text-secondary)' : '#fbbf24' }}>
                      {Number(o.current_stock).toLocaleString()} {o.unit}
                    </span>
                  </button>
                ))}
                {shown.length > 80 && (
                  <div style={{ padding: 8, textAlign: 'center', fontSize: 11, color: 'var(--text-muted)' }}>
                    {shown.length - 80} more — narrow the search
                  </div>
                )}
              </div>
            </>
          ) : (
            /* ── Step 2: confirm what will be created ──────────────────────── */
            <>
              {loading && <div style={{ padding: 20, textAlign: 'center', fontSize: 12, color: 'var(--text-muted)' }}>Reading…</div>}
              {preview && (
                <>
                  <div style={{ ...ROW, marginBottom: 12 }}>
                    <span style={{ ...LABEL, width: 84 }}>Oil</span>
                    <span style={{ fontSize: 13, color: 'var(--text-primary)', flex: 1 }}>{preview.oil.name}</span>
                    <span style={{ fontFamily: 'monospace', fontSize: 11, color: 'var(--text-muted)' }}>{preview.oil.code}</span>
                  </div>

                  <label style={{ ...LABEL, display: 'block', marginBottom: 5 }}>Product title</label>
                  <input
                    value={title} onChange={e => setTitle(e.target.value)}
                    style={{ width: '100%', padding: '9px 12px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 7, color: 'var(--text-primary)', fontSize: 13, marginBottom: 4 }}
                  />
                  <p style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 14, lineHeight: 1.5 }}>
                    Marketing can rename this on the store at any time — the codes below are the link, not the name.
                  </p>

                  {/* Which collection it belongs to. Chosen at registration, not
                      patched afterwards: once ten Archive fragrances exist, it
                      is ten records to update instead of ten born correct. */}
                  <label style={{ ...LABEL, display: 'block', marginBottom: 5 }}>Collection</label>
                  <div style={{ display: 'flex', gap: 8, marginBottom: 4 }}>
                    {[['library', 'Library'], ['archive', 'Archive']].map(([v, l]) => (
                      <button key={v} type="button" onClick={() => setUnit(v)}
                        style={{
                          flex: 1, padding: '8px 12px', borderRadius: 7, fontSize: 12, fontWeight: 600, cursor: 'pointer',
                          background: unit === v ? 'rgba(251,191,36,0.12)' : 'var(--surface-2)',
                          border: `1px solid ${unit === v ? 'rgba(251,191,36,0.5)' : 'var(--border)'}`,
                          color: unit === v ? '#fbbf24' : 'var(--text-muted)',
                          transition: 'border-color .15s, background .15s',
                        }}>{l}</button>
                    ))}
                  </div>
                  <p style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 14, lineHeight: 1.5 }}>
                    Decides which collection this reports under. It does not change the oil
                    rules or how it is produced — that stays with the segment.
                  </p>

                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
                    <span style={LABEL}>Will be created</span>
                    <span style={{ ...LABEL, color: 'var(--accent-text)' }}>Number {preview.number}</span>
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {(preview.lines || []).map(l => {
                      const off = skip.includes(l.master)
                      return (
                        <button key={l.master}
                          onClick={() => setSkip(off ? skip.filter(m => m !== l.master) : [...skip, l.master])}
                          style={{ ...ROW, cursor: 'pointer', width: '100%', textAlign: 'left', opacity: off ? 0.4 : 1 }}>
                          <span style={{
                            width: 16, height: 16, borderRadius: 4, flexShrink: 0,
                            border: `1px solid ${off ? 'var(--border)' : 'var(--accent-text)'}`,
                            background: off ? 'transparent' : 'var(--accent-text)',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                          }}>{!off && <Check size={11} color="#1a1a1a" />}</span>
                          <span style={{ fontSize: 13, color: 'var(--text-primary)', width: 108 }}>{l.format}</span>
                          <span style={{ fontFamily: 'monospace', fontSize: 12, fontWeight: 700, color: 'var(--text-primary)', flex: 1 }}>{l.sku}</span>
                          <span style={{ fontSize: 12, color: l.price == null ? '#fbbf24' : 'var(--text-secondary)' }}>
                            {l.price == null ? 'no price' : `$${Number(l.price).toFixed(2)}`}
                          </span>
                        </button>
                      )
                    })}
                  </div>

                  {(preview.warnings || []).map((w, i) => (
                    <div key={i} style={{ ...ROW, alignItems: 'flex-start', marginTop: 10, background: 'rgba(251,191,36,0.07)', borderColor: 'rgba(251,191,36,0.2)' }}>
                      <AlertTriangle size={14} color="#fbbf24" style={{ flexShrink: 0, marginTop: 1 }} />
                      <span style={{ fontSize: 12, color: '#fbbf24', lineHeight: 1.5 }}>{w}</span>
                    </div>
                  ))}
                </>
              )}
            </>
          )}
        </div>

        <div className="modal-footer">
          {done ? (
            <>
              <button className="btn btn-secondary" onClick={copyAll}><Copy size={13} /> Copy codes</button>
              {!done.store?.ok && (
                <button className="btn btn-secondary" onClick={retryPublish} disabled={saving}>
                  {saving ? 'Retrying…' : 'Retry on Shopify'}
                </button>
              )}
              <button className="btn btn-primary" onClick={onClose}>Done</button>
            </>
          ) : oil ? (
            <>
              <button className="btn btn-secondary" onClick={() => { setOil(null); setPreview(null) }}>Back</button>
              <button className="btn btn-primary" onClick={register} disabled={saving || !preview || !title.trim() || lines.length === 0}>
                {saving ? 'Registering…' : `Register ${lines.length} format${lines.length === 1 ? '' : 's'}`}
              </button>
            </>
          ) : (
            <button className="btn btn-secondary" onClick={onClose}>Cancel</button>
          )}
        </div>
      </div>
    </div>
  )
}
